### ISSUE TITLE
relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by teto** [dzhou121/gonvim#1]
When running the advised command:
LANG=C go get -u github.com/dzhou121/gonvim/cmd/gonvim 

I have :
```
# github.com/dzhou121/ui
/usr/bin/x86_64-linux-gnu-ld.bfd.real: ../go/src/github.com/dzhou121/ui/libui_linux_amd64.a(libui-combined.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld.bfd.real: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status

```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
```

I am not familiar with go so not sure how to fix it.? Gcc is gcc-6.real (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005. Might be a linking issue ?

**Comment by dzhou121** [comment]
Do you have gtk3 installed?

**Comment by teto** [comment]
libgtk-3 is installed and works. I met a similar error once, and it seemed due to a bug in the gcc linker. Changing to the new linker "gold" solved that problem.

**Comment by dzhou121** [comment]
Excellent. Is it working? I only tested it on Fedora but should work on all Linux.

**Comment by teto** [comment]
Sry I was not clear, I meant in that other project changing the linker solved the problem. So I tried to compile libui myself and replace the gonvim one:
`mkdir build && cmake -DBUILD_SHARED_LIBS=OFF .. && make && cp out/libui.a $GOPATH/src/github.com/dzhou121/ui/libui_linux_amd64.a`
and now it "works".

The UI looks weird though
https://transfer.sh/D93sH/2017-05-11-195900_767x916_scrot.png

(I run a HEAD nvim so that might be it ?).

**Comment by dzhou121** [comment]
The font rendering had some bug and I just fixed it.

Please run ```go get -u``` to update to the latest and try it again

**Comment by teto** [comment]
I updated both libui and gonvim yet it doesn't seem to change a thing for me. Was the bug in gonvim ?

I can't pass a --version flag to gonvim else I would have pasted it here

**Comment by dzhou121** [comment]
It might be that the update didn't pull the latest code because of the ```libui_linux_amd64.a``` change? Probably you need to ```git pull``` manually to make sure the gonvim source code is update to date.

**Comment by teto** [comment]
I just reran the go get command and it seems to work. Weird :s 
Thanks for the help
