### ISSUE TITLE
Unable to attach nvim to UI

### ISSUE THREAD

**Issue by serussell** [dzhou121/gonvim#10]
**Environment:**
NVIM v0.2.0-1171-g4566f7c7c
go version go1.8 linux/amd64
Linux sting 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux

**Behavior**
gonvim installed cleanly and without warnings or errors with `go get`.  Upon execution, a window flashes and exits, throwing this error:
```
➜  ~ gonvim

(gonvim:6994): Gtk-WARNING **: Theme parsing error: gtk.css:1:62: Failed to import: The resource at “/org/gnome/gnomishdark/gtk-main.css” does not exist
nvim attach UI error nvim:nvim_ui_attach validation: No such ui option
```
The exit code is 0.

**Comment by thibthibaut** [comment]
I have the same issue on Ubuntu 14.04 and on MacOS X Sierra
When I run it a window flashes and I get this output 
`nvim attach UI error nvim:nvim_ui_attach validation: No such ui option`

**Comment by dzhou121** [comment]
Please upgrade nvim to version 0.2

**Comment by serussell** [comment]
Confirmed fix.
