### ISSUE TITLE
Problem running gonvim on OSX and Go 1.7

### ISSUE THREAD

**Issue by fpietka** [dzhou121/gonvim#11]
gonvim doesn't launch, and I don't have much information:
```
$ go get -u github.com/dzhou121/gonvim/cmd/gonvim
$ gonvim
Killed: 9
```

Using go 1.7:
```
$ go version
$ go version go1.7.6 darwin/amd64
```

**Comment by dzhou121** [comment]
What is the version of your macOS and nvim?

**Comment by fpietka** [comment]
OSX version is 10.12.3, NVIM v0.2.0

**Comment by dmajere** [comment]
It fails even on 
```
import _ "github.com/dzhou121/ui"
```

**Comment by dmajere** [comment]
Ok, this one seems related to this: https://github.com/golang/go/issues/19734
Update to go1.8.1 and it should work fine.

**Comment by dzhou121** [comment]
@fpietka can you please update to the latest golang as @dmajere suggested 

@dmajere thanks for pointing this

**Comment by fpietka** [comment]
ok, I confirm it is related to Go version.

Using 1.8 I have another issue (`Terminating app due to uncaught exception 'NSInternalInconsistencyException'`), but I can create another issue about that if I can't solve it myself.
