### ISSUE TITLE
I can't change the font

### ISSUE THREAD

**Issue by hrqmonteiro** [dzhou121/gonvim#116]
![2021-01-27_19-31](https://user-images.githubusercontent.com/17055027/106062949-61d91900-60ef-11eb-95e5-7ca59a68b080.png)

My font is very buggy (because is not set to a NerdFont), and i can't change it.

I did as said on the Wiki, to edit the `ginit.vim` with the options:

```
GuiFont PragmataPro Nerd Font:h13
GuiLinespace 6
```

But it has no effect. Also, where should i put this `ginit.vim` file? You don't specify. I tried both `~/.config/nvim` and `~/.gonvim`, but it didn't work in neither.

**Comment by bio** [comment]
@hrqmonteiro, you can try a fork https://github.com/akiyosi/goneovim 
I hope [config docs](https://github.com/akiyosi/goneovim/wiki/Usage#configuration) will be helpful.
