### ISSUE TITLE
About removing the fork label from my forked repository goneovim

### ISSUE THREAD

**Issue by akiyosi** [dzhou121/gonvim#117]
@dzhou121 
Hi :D 
I have forked your repository, continued to maintain it and now the star count has exceeded the original gonvim. 

https://github.com/akiyosi/goneovim/stargazers

So I am considering contacting Github Support to remove the forked label so that goneovim can be seen by more people.

Before contacting Github Support, I wanted to get your thoughts first.
Do you have any opinions about removing the forked label from goneovim?

Please note that I will continue to keep your credit in the README of the goneovim project even after I remove the forked label.

**Comment by dzhou121** [comment]
@akiyosi 

Yes of course I think it makes sense for you to remove the forked label. If Github Support needs any information from me, I'll be more than happy to. 

You've done a great job on goneovim!

**Comment by akiyosi** [comment]
@dzhou121 
I appreciate your endorsement!
I will contact Github support then.
