### ISSUE TITLE
How to check gonvim is executed?

### ISSUE THREAD

**Issue by Shougo** [dzhou121/gonvim#17]
I want to add support gonvim in my plugins.
So I want to check gonvim is executed.

**Comment by dzhou121** [comment]
How about a global variable ```g:gonvim_running```

i.e., I'll ```let g:gonvim_running=1``` when gonvim is initiated.

**Comment by Shougo** [comment]
> i.e., I'll let g:gonvim_running=1 when gonvim is initiated.

OK.  It is nice.

**Comment by dzhou121** [comment]
I've added it now. 113ac80db616e7926cb0f35a2730433091cd22ca

**Comment by Shougo** [comment]
Thank you.
