### ISSUE TITLE
wrong keyboard layout.

### ISSUE THREAD

**Issue by teto** [dzhou121/gonvim#2]
I use a French layout (azerty) but gonvim seems to interpret it as a qwerty so if I type 'a', 'q' is printed. That's quite strange.

**Comment by dzhou121** [comment]
Please rebuild with latest github.com/dzhou121/ui or rebuild github.com/dzhou121/libui

**Comment by teto** [comment]
I deleted my ~/go/github.com/dzhou121 folder and redownloaded everything without more success. Any information that could help ?

**Comment by dzhou121** [comment]
Have you tried to re-compile the latest libui?

**Comment by teto** [comment]
Yes I did but this pulled very few commits (~2 or 4). Maybe @clason can give a try to confirm or not if it's a local problem ?

**Comment by clason** [comment]
I have exactly the same problem (German keyboard layout, special characters not working), and re-installing everything from scratch doesn't help either.

**Comment by dzhou121** [comment]
I just tested myself and the latest libui should solve it. You might need to delete the go build caches.

**Comment by clason** [comment]
I deleted the whole GOROOT folder before reinstalling.

On 31 May 2017 18:14, dzhou121 <notifications@github.com> wrote:

I just tested myself and the latest libui should solve it. You might need to delete the go build caches.

**Comment by dzhou121** [comment]
Do you mean GOPATH? So effectively you just need to delete GOPATH/pkg

**Comment by clason** [comment]
I think so - I deleted ~/go, which is the default installation directory for me.

On 31 May 2017 18:23, dzhou121 <notifications@github.com> wrote:

Do you mean GOPATH? So effectively you just need to delete GOPATH/pkg

**Comment by dzhou121** [comment]
@clason I just updated libui_linux_amd64.a in ui and you might want to delete GOPATH/pkg and do go get -u again. Please make sure dzhou121/ui is latest as well.

**Comment by clason** [comment]
Sorry, still no change. I just 

1. reinstalled go 1.8.3 (via homebrew on OS X 10.12.5)
2. deleted `~/go`
3. did `go get -u github.com/dzhou121/gonvim/cmd/gonvim`
4. ran `cd ~/go/bin; ./gonvim`

Same behavior as before.

**Comment by dzhou121** [comment]
Ah @clason you are on macOS. I thought you were on Linux as @teto

**Comment by clason** [comment]
I'm using both, with identical problems, but I can only test macOS at the moment.

**Comment by clason** [comment]
Now that I have direct access to a linux machine again, I can report that it does work there. (No change for macOS.)

**Comment by dzhou121** [comment]
Please try the latest Gonvim release.

**Comment by clason** [comment]
Still not working on macOS 10.12.6, I'm afraid. (Also, I can't run the `gonvim.app` binary, I have to run `gonvim-bin` from the command line.)

**Comment by dzhou121** [comment]
Does neovim-qt works fine for you?

**Comment by clason** [comment]
It does on Linux, but there's no binary for macOS to compare. (I can't compile it myself here.)

**Comment by dzhou121** [comment]
>  There seems to be a multi-byte problem.

Can you please clarify?

**Comment by clason** [comment]
I'll try. If I type `öööööö`, I see

```Ã Ã Ã ```

(note the space after `Ã`, so six characters in total); typing `<enter>` turns this into

```ÃÃÃÃÃÃ```

(Copy&Paste via the system keyboard gives `√É√É√É√É√É√É`...) The result is identical if I write `ä`, `ü`, `ß` etc.)

**Comment by dzhou121** [comment]
I might know what the problem is. I'll fix.

**Comment by teto** [comment]
azerty works with latest version except for some characters, e.g. 'é' will generate a 'Ã'

**Comment by dzhou121** [comment]
I've updated release v0.1. Please try again.

**Comment by clason** [comment]
Yes, it works now, thank you very much! (Although double-clicking on the .app bundle still does nothing -- should I open a new issue for this, and if so, how could I provide additional information?)

**Comment by teto** [comment]
works here too thanks !
