### ISSUE TITLE
Running gonvim exited with Message Killed : 9 macOS Sierra

### ISSUE THREAD

**Issue by smitajit** [dzhou121/gonvim#30]
after successfull go get -u github.com/dzhou121/gonvim/cmd/gonvim
running gonvim exited with Message Killed : 9
Returned error code 137

OS : MacOs Sierra
GO version : go version go1.7 darwin/amd64
nvim version : NVIM v0.2.0

**Comment by dzhou121** [comment]
Please try the latest release of Gonvim
