### ISSUE TITLE
Long completion lists do not display properly

### ISSUE THREAD

**Issue by wbthomason** [dzhou121/gonvim#31]
The popup for completions seems to have a bug related to displaying long lists.

For example:
![Python import list](https://user-images.githubusercontent.com/3729908/27008249-ef2b15a4-4e3a-11e7-8818-7fe31efd7432.png)
![LaTeX citations](https://user-images.githubusercontent.com/3729908/27008250-ef2c7926-4e3a-11e7-864f-e65372526f49.png)

I'm on Arch Linux with Neovim 0.2.0 and the latest gonvim. I can give more diagnostic information if that helps.

**Comment by dzhou121** [comment]
Please try the latest release of gonvim. It should be fixed.

**Comment by clason** [comment]
Looks good for me (on macOS)!

**Comment by wbthomason** [comment]
I can't compile the new version on Arch, but I think it's a problem with the `therecipe/qt/core` dependency and not gonvim. This does appear to be fixed in the binary release, though. Thanks!
