### ISSUE TITLE
denite.nvim is freezed

### ISSUE THREAD

**Issue by Shougo** [dzhou121/gonvim#33]
I have tested the latest release versionof gonvim.
It works!

But if I use denite.nvim, gonvim is freezed.
It does not happened in the previous version.

Can you test it?

**Comment by dzhou121** [comment]
Can you please give me a screenshot of the freeze?

**Comment by Shougo** [comment]
![denite](https://user-images.githubusercontent.com/41495/27270417-d156a9ca-54f8-11e7-8e0b-3c542695907a.png)

**Comment by dzhou121** [comment]
Can you please try the latest release. There will be a delay in denite though. But you can fix it by disabling gonvim split drawing

```let g:gonvim_draw_split = 0```

**Comment by Shougo** [comment]
Sorry, I could not find the latest release...

https://github.com/dzhou121/gonvim/releases

**Comment by dzhou121** [comment]
Just re-download v0.1

**Comment by Shougo** [comment]
The freeze is fixed but CPU 100%...

**Comment by dzhou121** [comment]
How about ```let g:gonvim_draw_split = 0```

**Comment by Shougo** [comment]
It seems same.
After exit denite, gonvim CPU usage is very very high.
It is not usable... :-(

**Comment by dzhou121** [comment]
Is the CPU 100% without entering denite?

**Comment by Shougo** [comment]
No.
If use denite only.

**Comment by dzhou121** [comment]
Have you restarted gonvim after setting let g:gonvim_draw_split = 0,not re-sourcing

**Comment by Shougo** [comment]
I have set it in ginit.vim.
No difference.

**Comment by dzhou121** [comment]
Please put in init.vim and restart gonvim

**Comment by Shougo** [comment]
Ah, OK.  It works.
But ctrl keymappings don't work for example `<C-h>`, `<C-o>`,...

**Comment by Shougo** [comment]
You can test it by the following:

`:echo getchar()` and press `<c-g>`.
It is the different result between nvim and gonvim.

**Comment by dzhou121** [comment]
Did the keymap work in previous versions?

**Comment by Shougo** [comment]
I think yes...

**Comment by dzhou121** [comment]
Please re-download v0.1 release. It should be fixed.

**Comment by Shougo** [comment]
The problem is fixed.
Thank you!
