### ISSUE TITLE
windows version

### ISSUE THREAD

**Issue by Averey** [dzhou121/gonvim#34]
This GUI is awesome!! I love it at the first glance! But, my major system is Windows.  So, there is any plan for Windows version?

**Comment by dzhou121** [comment]
The Windows version is available at https://github.com/dzhou121/gonvim/releases

Please try it out.

**Comment by Shougo** [comment]
Dup of #13?

**Comment by Averey** [comment]
@dzhou121 Thx, I will try it!!
@Shougo thank you for reference, I should check the issues list before opening an issue
