### ISSUE TITLE
Minor graphical bug when resizing windows

### ISSUE THREAD

**Issue by oliverrausch** [dzhou121/gonvim#36]
```
gonvim version:       0.1
nvim version:         0.2.0
platform:             linux
desktop-environment:  xfce4
```

# Steps to reproduce
1. Create a vertical split (type :vsp)
2. Maximise the gonvim window
3. Make the splits equal size (type Ctrl-W =)

# Screenshots
## Current behavior

![Current](http://i.imgur.com/3y3ZZZg.png)

## Expected behavior

![Expected](http://i.imgur.com/IryC7HM.png)

**Comment by dzhou121** [comment]
Hi, can you please try the latest release.

**Comment by oliverrausch** [comment]
The issue remains unresolved in the current nightly build

**Comment by dzhou121** [comment]
Please try the latest nightly release.

**Comment by oliverrausch** [comment]
Issue is resolved in the latest release. :+1:
