### ISSUE TITLE
Opening files currently opened by another Neovim instance freezes gonvim interface

### ISSUE THREAD

**Issue by wbthomason** [dzhou121/gonvim#37]
As the title indicates. If I open `foo.txt` in terminal Neovim and then try to open `foo.txt` in gonvim, the gonvim interface freezes and does not display any updates in response to keypresses. However, if `:q<CR>` is entered, gonvim unfreezes into a blank buffer.

**Comment by dzhou121** [comment]
I can't replicate this. Can you please send some screenshots.

**Comment by dzhou121** [comment]
Could be the same issue like this https://github.com/equalsraf/neovim-qt/issues/292

**Comment by wbthomason** [comment]
Ah, I wasn't aware of that issue. Yes, I think that would explain it. Thanks!
