### ISSUE TITLE
Cursor does not display correctly

### ISSUE THREAD

**Issue by wbthomason** [dzhou121/gonvim#4]
The cursor renders at a fixed location in the buffer, and does not move. It reacts to mode changes (highlighting differently for insert vs normal vs visual), and the rest of the UI indicates that the actual cursor is moving (relative line numbers change, text can be inserted at different locations, etc.), but the cursor never moves. In what may be a related issue, the various popups (completion, fuzzy-finder, lint error) seem to not be displaying. 

I'm on Arch Linux with Neovim 0.2.0 and the latest `gonvim`. This behavior occurs even when `gonvim` is started as `gonvim -u NONE <file>`, so I don't think it's due to any of my plugins or configuration.

**Comment by sonicpp** [comment]
Same issue on Antergos with neovim 0.2.0-2

**Comment by dzhou121** [comment]
Can you please run ```go get -u github.com/dzhou121/gonvim/cmd/gonvim``` to update to latest gonvim and try again.

**Comment by sonicpp** [comment]
New version fixes it for me, even tabs (tabnew, tabpprev etc) are working now!

**Comment by wbthomason** [comment]
Confirmed; the latest version fixes the problems I was seeing. Closing. Thanks!
