### ISSUE TITLE
Split window mapping does not work.

### ISSUE THREAD

**Issue by HiCodin** [dzhou121/gonvim#43]
Below commands are not working in `gonvim` but its working in `neovim-qt `client
nmap < c-k >  :wincmd k<CR>
nmap < c-j >  :wincmd j<CR>
nmap < c-h >  :wincmd h<CR>
nmap < c-l >  :wincmd l<CR>

**Comment by dzhou121** [comment]
Can you please exec ```:echo getchar()``` and press ```<C-h>```, and let me know the output?

**Comment by HiCodin** [comment]
~@<80>~@^D^D^H
~@<80>~@^D^D^J
~@<80>~@^D^D^K
~@<80>~@^D^D^L

I forgot to mention that this is on Windows 8.1

**Comment by Shougo** [comment]
Hm...
Similar issue is exists.
https://github.com/dzhou121/gonvim/issues/35

**Comment by dzhou121** [comment]
Yeah, it looks you pressed the windows key.

**Comment by HiCodin** [comment]
@dzhou121  I just changed to meta key for the time being. Is there any reason why this one seems like pressing windows key like you mention?

**Comment by dzhou121** [comment]
Maybe I should disable the windows key just like neovim-qt does. Fixing now.

**Comment by dzhou121** [comment]
Please re-download v0.1 and try again.

**Comment by HiCodin** [comment]
@dzhou121 Its working now. Thanks for the quick fix. ! 👍

**Comment by Shougo** [comment]
Closing?
