### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by jerrytaffy** [dzhou121/gonvim#45]
Hi,

I use "get get" to get an error.

Detail:

go get -u -v github.com/dzhou121/gonvim/cmd/gonvim
github.com/dzhou121/gonvim (download)
github.com/dzhou121/gonvim-fuzzy (download)
github.com/junegunn/fzf (download)
github.com/mattn/go-isatty (download)
github.com/mattn/go-runewidth (download)
github.com/neovim/go-client (download)
github.com/therecipe/qt (download)
github.com/dzhou121/gonvim
# github.com/dzhou121/gonvim
go1.8/src/github.com/dzhou121/gonvim/editor.go:82: e.signal.GuiSignal undefined (type *editorSignal has no field or method GuiSignal)
go1.8/src/github.com/dzhou121/gonvim/editor.go:86: e.signal.RedrawSignal undefined (type *editorSignal has no field or method RedrawSignal)
go1.8/src/github.com/dzhou121/gonvim/editor.go:317: undefined: NewEditorSignal
go1.8/src/github.com/dzhou121/gonvim/locpopup.go:53: editor.signal.ConnectLocpopupSignal undefined (type *editorSignal has no field or method ConnectLocpopupSignal)
go1.8/src/github.com/dzhou121/gonvim/locpopup.go:100: editor.signal.LocpopupSignal undefined (type *editorSignal has no field or method LocpopupSignal)
go1.8/src/github.com/dzhou121/gonvim/locpopup.go:181: editor.signal.LocpopupSignal undefined (type *editorSignal has no field or method LocpopupSignal)
go1.8/src/github.com/dzhou121/gonvim/statusline.go:255: editor.signal.ConnectStatuslineSignal undefined (type *editorSignal has no field or method ConnectStatuslineSignal)
go1.8/src/github.com/dzhou121/gonvim/statusline.go:259: editor.signal.ConnectLintSignal undefined (type *editorSignal has no field or method ConnectLintSignal)
go1.8/src/github.com/dzhou121/gonvim/statusline.go:262: editor.signal.ConnectGitSignal undefined (type *editorSignal has no field or method ConnectGitSignal)
go1.8/src/github.com/dzhou121/gonvim/statusline.go:267: editor.signal.StatuslineSignal undefined (type *editorSignal has no field or method StatuslineSignal)
go1.8/src/github.com/dzhou121/gonvim/statusline.go:267: too many errors

**Comment by dzhou121** [comment]
It takes some effort to build now. You can download pre-built binary for your platform.

**Comment by wbthomason** [comment]
@jerrytaffy If you use Arch Linux, I've also made an AUR package for the binary: https://aur.archlinux.org/packages/gonvim

**Comment by jerrytaffy** [comment]
@wbthomason thanks for your help. But I use the macos.

**Comment by joereynolds** [comment]
It would be nice to not have to rely on the pre-built binaries. These aren't always up-to-date and there are some commits that interest me that aren't in the release (fix keypress, for example)

**Comment by dzhou121** [comment]
It uses QT as backend so wouldn't be straight forward to install. The binary is actually the latest commit. I was too lazy to create a new release, and just updated the current one.

**Comment by mdafanasev** [comment]
@wbthomason I've installed your package from AUR and it requires libQt5Quick.so.5, but x86_64 version of qt5-multimedia doesn't contain it.. How can I fix it?

**Comment by wbthomason** [comment]
@mdafanasev It looks like that's from `qt5-declarative`. I'll add that to the dependencies list. Thanks for finding this error; I have all of the `qt5` meta-package installed on my machine, so there are a few dependencies that I've missed. Let me know if you still have trouble (though maybe we shouldn't hijack this thread...)

@dzhou121 While I absolutely understand not wanting to make a new release after every change, it does make it difficult to keep packages up to date if you update the release without bumping the version number.  I'm not sure what the best solution to this is, though - I spent a while trying to get things to build with the new QT dependencies, and wasn't able to make things work.

**Comment by clason** [comment]
@dzhou121 If you keep the binaries up-to-date, you could call them "nightly" instead of tagging them with a version and add the last commit id to the description. (You can probably automate this.)

**Comment by dzhou121** [comment]
@clason Thanks for the note. It's done now.

**Comment by wbthomason** [comment]
@dzhou121 Do you plan to make more "stable" (i.e. v0.1, v0.2, etc.) releases, or just continue to update the nightly release? If you'll just be doing the nightly release, I'll update my AUR package to install from there instead of the latest v0.x release. Thanks!

**Comment by dzhou121** [comment]
@wbthomason I think I'll just update the nightly release for now. And v0.2 v0.3 etc when I can add more externalised items which is depending on Neovim external related PRs.

**Comment by wbthomason** [comment]
@dzhou121 Ok, thanks for the info. I will still make the AUR package use the nightly release for now, I think.
