### ISSUE TITLE
No anti-alaising on fonts with 1440p external monitor

### ISSUE THREAD

**Issue by TimothyKrell** [dzhou121/gonvim#47]
Fonts look great on my MacBook Pro's screen, but when I move the window to my external Dell U3415W monitor, the fonts appear to be missing anti-aliasing. The tab and bottom bar fonts render correctly, but the fonts inside the editor do not.
![screen shot 2017-06-29 at 8 04 02 am](https://user-images.githubusercontent.com/1585669/27687298-4affe4b4-5ca4-11e7-985e-02093c67587f.png)
![screen shot 2017-06-29 at 8 05 15 am](https://user-images.githubusercontent.com/1585669/27687297-4afe253e-5ca4-11e7-8742-b628fad63b4d.png)

**Comment by dzhou121** [comment]
Please try the latest nightly release.

**Comment by TimothyKrell** [comment]
Yep! Fixed in nightly. Thanks! 👍
