### ISSUE TITLE
Typing a colon results in a SIGSEGV

### ISSUE THREAD

**Issue by xyproto** [dzhou121/gonvim#5]
A window shows up when starting gonvim, but typing `:` immediatly crashes the application and outputs this on the console:

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x438a2a9]

This is using:

* Go 1.8.3
* macOS Sierra 10.12.5
* Latest gonvim commit hash: 00ced37bb34846cf628a293141f3c5ee7e948b19

**Comment by dzhou121** [comment]
Hi, can you please run ```go get -u github.com/dzhou121/gonvim/cmd/gonvim``` to update to the latest and try again.

**Comment by xyproto** [comment]
Works now, thanks :+1:
