### ISSUE TITLE
Mouse support to control windows/splits/tabs

### ISSUE THREAD

**Issue by edubxb** [dzhou121/gonvim#51]
Would be nice if the mouse can be used to manage windows/splits/tabs for closing, resizing, etc.

**Comment by marciol** [comment]
In the same sense would be nice to allow the basic mouse usage, point the cursor and make selections.

**Comment by ellis** [comment]
It'd also be great to be able to scroll with the mouse wheel - I miss not being able to conveniently scroll through terminal windows. (Loving gonvim, btw!)

**Comment by akiyosi** [comment]
hi,
Do you have any problems with this issue ?

**Comment by Mte90** [comment]
ping for this ticket

**Comment by akiyosi** [comment]
The repository I forked supports the mouse/touchpad for tab, scrolling.
https://github.com/akiyosi/gonvim

There are some bugs, but I intend to fix it recently!
