### ISSUE TITLE
How do you open the file sidebar shown in your screenshots?

### ISSUE THREAD

**Issue by ellis** [dzhou121/gonvim#53]
Could you please explain how you open the file explorer sidebar shown in your screenshots?  I'm running on Linux, if that makes any difference with regard to menus or anything (no menu bar in linux).

**Comment by adrianofoschi** [comment]
+1

**Comment by dzhou121** [comment]
Hi, the file explorer sidebar is Nerdtree Vim plugin https://github.com/scrooloose/nerdtree
