### ISSUE TITLE
Development guide

### ISSUE THREAD

**Issue by kristijanhusak** [dzhou121/gonvim#66]
Hi, can you add development guide?

I would like to contribute, but i'm stuck at setting up the local dev environment. I'm not really familiar with Qt, and wasn't able to install it properly.

**Comment by dzhou121** [comment]
Hi, thanks for your interest. 

I've now added how to install 
https://github.com/dzhou121/gonvim/blob/master/README.md#manual-installation

**Comment by kristijanhusak** [comment]
Thanks!

**Comment by kristijanhusak** [comment]
I have the same issue like this one https://github.com/dzhou121/gonvim/issues/64.
Do you know a way to fix it?

Here's what i get:
```sh
$ go get -u github.com/dzhou121/gonvim/
# github.com/dzhou121/gonvim-fuzzy/rplugin/go/fzf
src/github.com/dzhou121/gonvim-fuzzy/rplugin/go/fzf/fzf.go:221:27: cannot use chars (type util.Chars) as type *util.Chars in argument to algo.FuzzyMatchV2
# github.com/therecipe/qt/core
core.cpp:9:25: fatal error: QTextDocument: No such file or directory
compilation terminated.
```

**Comment by gasparch** [comment]
And my error is 

```
# github.com/dzhou121/gonvim-fuzzy/rplugin/go/fzf
github.com/dzhou121/gonvim-fuzzy/rplugin/go/fzf/fzf.go:221:27: cannot use chars (type util.Chars) as type *util.Chars in argument to algo.FuzzyMatchV2
# github.com/therecipe/qt/core
core.cpp:9:30: fatal error: QAbstractAnimation: No such file or directory
```

I want to pack gonvim into Ubuntu Snap - and cannot get it compiling properly ;)))

**Comment by dzhou121** [comment]
Is Qt installed and have you ran qtsetup successfully?

**Comment by kristijanhusak** [comment]
@dzhou121 my bad, qtsetup used wrong version, it tried 5.9.1, but i installed 5.9.2. passing in -qt_version 5.9.2 did the trick :)
When building, i get the same error from the related issue for the fzf, and adding & to the chars fix the build.

**Comment by gasparch** [comment]
I have to `qtsetup` :) Do you have idea which package installs it? I don't want to compile whole Qt :)

**Comment by kristijanhusak** [comment]
@gasparch it should be in your ~/go/bin directory after you fetch the go qt package.
