### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Shougo** [dzhou121/gonvim#72]
The nightly build is old.
Can you update it?
I want to test the latest version.

https://github.com/dzhou121/gonvim/releases

**Comment by edubxb** [comment]
Hello @dzhou121 are there any plans to have a new release with the latest changes?

Thanks!

**Comment by dzhou121** [comment]
The latest with external cmdline etc is released now.

**Comment by edubxb** [comment]
Thanks @dzhou121

**Comment by Shougo** [comment]
I have tested the latest version.
It works charm!
