### ISSUE TITLE
Can't use any of the workspace commands

### ISSUE THREAD

**Issue by joereynolds** [dzhou121/gonvim#80]
The docs mention

> GonvimWorkspaceNew       -  Create a new workspace
GonvimWorkspaceNext      -  Switch to the next workspace
GonvimWorkspacePrevious  -  Switch to the previous workspace
GonvimWorkspaceSwitch n  -  Switch to workspace n

When I try these in Gonvim, they are not present so don't do anything.
I've tried calling the command that this calls underneath `rpc_notify(0, ....` and that also doesn't work.

My steps were:

1. Download gonvim for linux from the releases page
2. Run it with `./gonvim.sh`
3. Attempt to use the commands

Am I doing something wrong here?

**Comment by joereynolds** [comment]
If I run `:command` there's nothing to do with Gonvim in there

**Comment by dzhou121** [comment]
Please try the latest v0.2.2 release.

**Comment by joereynolds** [comment]
That seems to have fixed it, thanks!
