### ISSUE TITLE
Can't build Gonvim-0.2.2

### ISSUE THREAD

**Issue by akiyosi** [dzhou121/gonvim#84]
Hi, I tryed to build the latest Gonvim but failed with the following error.

```
% go build
# github.com/dzhou121/gonvim/editor
_cgo_main.c:2:23: warning: unused parameter 'fn' [-Wunused-parameter]
_cgo_main.c:2:61: warning: unused parameter 'a' [-Wunused-parameter]
_cgo_main.c:2:68: warning: unused parameter 'c' [-Wunused-parameter]
_cgo_main.c:2:85: warning: unused parameter 'ctxt' [-Wunused-parameter]
_cgo_main.c:4:41: warning: unused parameter 'ctxt' [-Wunused-parameter]
_cgo_main.c:6:26: warning: unused parameter 'a' [-Wunused-parameter]
_cgo_main.c:6:33: warning: unused parameter 'c' [-Wunused-parameter]
_cgo_main.c:7:23: warning: unused parameter 'a' [-Wunused-parameter]
_cgo_main.c:7:30: warning: unused parameter 'c' [-Wunused-parameter]
# github.com/dzhou121/gonvim/editor
./editor.go:324:10: undefined: core.NewQChar11
```

my environment is;

```
qt: 5.9.3
golang: 1.9.1
```
Is it need a newest qt or golang ?

Furthermore, I got a different error when target is Windows.

```
% qtdeploy -docker build windows_32_shared

...

markdown.go:11:2: build constraints exclude all Go files in /home/user/work/src/github.com/therecipe/qt/webengine
```

**Comment by dzhou121** [comment]
You need the latest github.com/therecipe/qt

**Comment by dzhou121** [comment]
It can't build on windows because webengine is not supported on Windows.
https://github.com/therecipe/qt/wiki/FAQ#why-webengine-and-webview-are-not-working-

**Comment by akiyosi** [comment]
> You need the latest github.com/therecipe/qt

Thank you.
I updated therecipe/qt with the following steps and build it again gonvim, but it got the same error :(
1. delete current `GOPATH/github.com/therecipe/qt`
1. `go get -u -v github.com/therecipe/qt/cmd/...`
1. qtsetup
1. cd GOPATH/github.com/dzhou121/gonvim/editor/
1. qtmoc & go build


> It can't build on windows because webengine is not supported on Windows.
> https://github.com/therecipe/qt/wiki/FAQ#why-webengine-and-webview-are-not-working-

Understood.
Do you no longer support Windows?

**Comment by dzhou121** [comment]
Probably try to delete rcc* files in cmd/gonvim/?

**Comment by dzhou121** [comment]
Ideally when Go supports msvc build under windows, we can build qwebengine in windows as well. 

This is the issue of msvc for Go https://github.com/golang/go/issues/20982

**Comment by akiyosi** [comment]
> Probably try to delete rcc* files in cmd/gonvim/?

There is no rcc* files in cmd/gonvim/, github.com/dzhow121/gonvim/
Hmm... :(

> Ideally when Go supports msvc build under windows, we can build qwebengine in windows as well.
> 
> This is the issue of msvc for Go golang/go#20982

thank you. I will expect.

**Comment by dzhou121** [comment]
Looks like some cache is stuck somewhere. Maybe try to clean go PKG SRC and re-install qt binding and run qtsetup

**Comment by akiyosi** [comment]
I tried to your suggestion but I can not solve it :(
For now, I temporarily ignore the error with the following modification code.
```
editor/editor.go:324:10: core.NewQChar11  => core.NewQChar9
```

**Comment by akiyosi** [comment]
I got a reply to the following issue.

https://github.com/therecipe/qt/issues/538


> Yeah, those errors can happen if you use a different version of Qt than the author of gonvim.
> So your environment is not generating older code, but different code ...
> 
> I will try to find a way to fix those issues, but they are usually very rare.

What version of Qt are you using?

**Comment by dzhou121** [comment]
I'm using QT 5.10.0 downloaded from qt website (not the brew version) 

```
INFO[0000] GOOS:                        'darwin'
INFO[0000] GOARCH:                      'amd64'
INFO[0000] GOVERSION:                   'go1.10'
INFO[0000] GOROOT:                      '/usr/local/Cellar/go/1.10/libexec'
INFO[0000] GOPATH:                   *  '/Users/Lulu/go'
INFO[0000] GOBIN:                       '/Users/Lulu/go/bin'
INFO[0000] QT_HASH:                     'a76e7081468b0d9d554349b66b4971929f036ce7'
INFO[0000] QT_VERSION:                  '5.10.0'
INFO[0000] QT_VERSION_MAJOR:            '5.10.0'
INFO[0000] QT_DIR:                      '/Users/Lulu/Qt5.10.0'
INFO[0000] QT_STUB:                     'false'
INFO[0000] QT_DEBUG:                    'false'
INFO[0000] QT_QMAKE_DIR:                ''
INFO[0000] QT_WEBKIT:                   'false'
INFO[0000] QT_HOMEBREW:                 'false'
INFO[0000] XCODE_DIR:                   '/Applications/Xcode.app'

```
