### ISSUE TITLE
How to enable File-browse

### ISSUE THREAD

**Issue by telamon** [dzhou121/gonvim#85]
Hey what is that awesome folder-explorer/file-browser seen on the screenshots and how do I open such a buffer?

**Comment by Shougo** [comment]
https://github.com/dzhou121/gonvim/wiki/Configurations#workspace

**Comment by dzhou121** [comment]
That's https://github.com/scrooloose/nerdtree with https://github.com/ryanoasis/vim-devicons

**Comment by telamon** [comment]
Ah! vim-devicons! That's what I was missing! Thanks!

**Comment by dzhou121** [comment]
I plan to implement a GUI version of file explorer in Gonvim after the floating windows PR is merged in neovim.
