### ISSUE TITLE
输入法切换的问题

### ISSUE THREAD

**Issue by seaweedman** [dzhou121/gonvim#94]
系统：archlinux
在 `～/.config/nvim/init.vim` 中配置了输入法切换的插件，在命令行启动nvim,可以进行输入法的切换，正常输入中文，but在gonvim中无法切换，shift+space切换输入法时，退出了insert模式。

**Comment by akiyosi** [comment]
Hi,

It is probably not a problem of Gonvim, it is a problem of input-methods on Qt applications in your Arch-Linux.
please check some tools of input-method in arch-linux(fcitx, fcitx-qt5,...).

**Comment by seaweedman** [comment]
@akiyosi thank you. maybe, but I decide still 老老实实 use Atom, neovim not very helpful for me to improve code 效率.
